version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.0
    - 12.6.3
    - 12.7.0
    - 12.7.2
    - 12.7.3
    - 12.8.1
    - 12.8.3
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.1.1
    - 13.1.2
    - 13.1.3
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/babel__traverse"
    versions:
    - 7.11.0
  - dependency-name: "@reduxjs/toolkit"
    versions:
    - 1.5.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
